### ISSUE TITLE
FB: Return value of method without side effect is ignored

### ISSUE THREAD

**Issue by sbondorf** [NetCal/DiscoSNC#6]
In `SimpleOptimizer.java`, method `public double minimize(...)` there is this loop:

```
while(theta < maxTheta) {
	try {
		Math.min(optValue, bound.evaluate(theta));
		theta = theta+thetagranularity;
	} catch(ServerOverloadException | ThetaOutOfBoundException e) {
		theta = theta+thetagranularity;
	}
}
```
and Spotbugs rightfully complains that the result of `Math.min` is not used.
Note, that `bound.evaluate(theta)` cannot change theta as it is an immutable `double`.

Moreover, above this problematic loop, we find similar loops. For example:
```
while(theta < maxTheta) {
	try {
		optValue = Math.min(optValue, bound.evaluate(theta));
		theta = theta+thetagranularity;
	} catch(ServerOverloadException | ThetaOutOfBoundException e) {
		theta = theta+thetagranularity;
	}
}
```
They all assign `optValue = `. Is that assignment missing in the problematic loop?

**Comment by scriptkitty** [comment]
Yes, that assignment is missing the loop.
